Python 3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
a = 12
b = 21
b = 20
c = a
a = b
b = c
a
20
b
12
a
20
b
12
a,b = b,a
a
12
b
20
a,b = b,a # swapping of two variables

========= RESTART: D:/Batches/2022/Python Eve Reg/FibSeries.py =========
Enter a number : 10
0
1
1
2
3
5
8
13
21
34

========= RESTART: D:/Batches/2022/Python Eve Reg/WhileDemo'.py ========
0
1
2
3
4
5
6
7
8
9

========= RESTART: D:/Batches/2022/Python Eve Reg/WhileDemo'.py ========
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0Traceback (most recent call last):
  File "D:/Batches/2022/Python Eve Reg/WhileDemo'.py", line 3, in <module>
    print(a)
KeyboardInterrupt

========= RESTART: D:/Batches/2022/Python Eve Reg/WhileDemo'.py ========
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
import random
random.randint(1,100)
51
random.randint(1,100)
36
random.randint(1,100)
65
random.randint(1,100)
94
a = 12
b = 11
a + b
23
a - b
1
a / b
1.0909090909090908
a * b
132
a ** b
743008370688
2 ** 4
16
4 ** 8
65536
2 ** 3
8
10 ** 2
100
60 / 6
10.0
60 / 7
8.571428571428571
60 // 7
8
10 / 5
2.0
10 % 5
0
num = 10
guess = 45
num == guess
False
num > guess
False
num < guess
True
num >= guess
False
num != guess
True

= RESTART: D:/Batches/2022/Python Eve Reg/if_else.py
Number is odd...

= RESTART: D:/Batches/2022/Python Eve Reg/max_of_3.py
C is greatest...

= RESTART: D:/Batches/2022/Python Eve Reg/GuessTheNumber.py
Enter your guess : 45
You have guessed a greater number...

= RESTART: D:/Batches/2022/Python Eve Reg/GuessTheNumber.py
Enter your guess : 50
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
You have guessed a smaller number...
Traceback (most recent call last):
  File "D:/Batches/2022/Python Eve Reg/GuessTheNumber.py", line 15, in <module>
    print("You have guessed a smaller number...")
KeyboardInterrupt

= RESTART: D:/Batches/2022/Python Eve Reg/GuessTheNumber.py
Enter your guess : 50
You have guessed a smaller number...
Enter your guess : 60
You have guessed a smaller number...
Enter your guess : 70
You have guessed a greater number...
Enter your guess : 65
Congrats you have guessed the number...

= RESTART: D:/Batches/2022/Python Eve Reg/GuessTheNumber.py
Enter your guess : 50
You have guessed a smaller number...
Chances Left :: 4
Enter your guess : 70
You have guessed a smaller number...
Chances Left :: 3
Enter your guess : 90
You have guessed a greater number...
Chances Left :: 2
Enter your guess : 78
You have guessed a greater number...
Chances Left :: 1
Enter your guess : 74
You have guessed a greater number...
Chances Left :: 0

= RESTART: D:/Batches/2022/Python Eve Reg/GuessTheNumber.py
Enter your guess : 50
You have guessed a smaller number...
Chances Left :: 4
Enter your guess : 60
You have guessed a smaller number...
Chances Left :: 3
Enter your guess : 70
You have guessed a greater number...
Chances Left :: 2
Enter your guess : 64
You have guessed a smaller number...
Chances Left :: 1
Enter your guess : 68
You have guessed a greater number...
Chances Left :: 0
You Lose, Number was : 67
